### ISSUE TITLE
So, how to deploy it to heroku?

### ISSUE THREAD

**Issue by yuriychemodakovakv** [angular/universal-starter#122]
Sorry for the stupid question. And if it's not an appropriate place for this king of questions, please let me know where...

You said in http://stackoverflow.com/questions/35424790/hosting-angular2-on-heroku that this project is an answer on question "how to deploy on heroku?"

Could you please explain how exactly I can deploy it on heroku?

I've uploaded everything where, without dist, node_modules, typings.
Heroku says that it deployed app successfully (buildpack for node.js).
But when I open app, it shows me an error:
https://universal-starter.herokuapp.com/

**Comment by JayKan** [comment]
I was running into a similar issue while trying to deploy to heroku (https://secure-tundra-88312.herokuapp.com/).

Do we need to modify `main.node.ts` ExpressEngineConfig.platformProviders in order to deploy to Heroku?

**Comment by Teshel** [comment]
I'm having the same problem, and here is Heroku's log of the crash:

`$ heroku logs --tail`
`2016-07-13T22:08:29.390846+00:00 heroku[web.1]: State changed from crashed to starting`
`2016-07-13T22:08:33.816513+00:00 heroku[web.1]: Starting process with command 'node dist/server/index.js'`
`2016-07-13T22:08:36.139906+00:00 app[web.1]: module.js:341`
`2016-07-13T22:08:36.139917+00:00 app[web.1]:     throw err;`
`2016-07-13T22:08:36.139921+00:00 app[web.1]:     ^`
`2016-07-13T22:08:36.139922+00:00 app[web.1]:`
`2016-07-13T22:08:36.139923+00:00 app[web.1]: Error: Cannot find module '/app/dist/server/index.js'`
`2016-07-13T22:08:36.139923+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:339:15)`
`2016-07-13T22:08:36.139924+00:00 app[web.1]:     at Function.Module._load (module.js:290:25)`
`2016-07-13T22:08:36.139924+00:00 app[web.1]:     at Function.Module.runMain (module.js:447:10)`
`2016-07-13T22:08:36.139925+00:00 app[web.1]:     at startup (node.js:148:18)`
`2016-07-13T22:08:36.139926+00:00 app[web.1]:     at node.js:405:3`
`2016-07-13T22:08:37.175915+00:00 heroku[web.1]: Process exited with status 1`
`2016-07-13T22:08:37.203837+00:00 heroku[web.1]: State changed from starting to crashed`

The reason it can't find `dist/server/index.js` seems to be due to several things. The first is that Webpack is in devDependencies, and so it isn't getting installed on Heroku when it's set to production mode. If you set NPM to not use production mode, you can get it to install.

`$ heroku config:set NPM_CONFIG_production=false`
`$ heroku run bash`
`~ $ npm install`

The second reason it can't find `dist/server/index.js` is that Webpack is not being run automatically. I'm enough of a novice that I don't really know where to configure it to run automatically, but running it manually is fairly easy.

`~ $ webpack`

From there it's easy to verify the `index.js` exists where it should be. But the error still happens, even when you restart the dyno: it says it can't find `dist/server/index.js`. I'm at a loss here because the file obviously exists.

Another thing I noticed is that the node instance started by `index.js` is hardcoded to listen on port 3000, rather than using the port set for the environment. I trying changing it to use `process.env.PORT`, and even though it is possible to start the server manually, the app is still in a "crashed" state and so refreshing still gives you the error message that the application crashed.

**Comment by JayKan** [comment]
Very interesting @Teshel, after reviewing my heroku log I realized my error was slightly different than yours, instead of can't find `dist/server/index.js`, my error was can't find module `/app/dist/server/index.js`. (See attached log screenshot)

<img width="1426" alt="screen shot 2016-07-20 at 9 35 31 pm" src="https://cloud.githubusercontent.com/assets/1400300/17011389/82be219a-4ec2-11e6-8d0f-85960f9d9eb4.png">

**Comment by Teshel** [comment]
That looks like basically the same error I was getting. Those are the same files, notice that your logs also mention an error in process `node dist/server/index.js`. Heroku puts your project into `/app/ ` and runs everything from there, so one error message is just giving the full path and the other a local path.

Anywho, my solution to this issue was switching to [Vlado Tesanovic's Angular2 Express Starter](https://github.com/vladotesanovic/angular2-express-starter) which works with Heroku right out of the box. It uses SystemJS rather than Webpack so this might not be what you're looking for.

**Comment by yuriychemodakovakv** [comment]
@Teshel, it doesn't work as well https://my-express-starter.herokuapp.com/. Completely the same.

**Comment by Ignigena** [comment]
So there are a couple different issues here preventing a quick deployment to Heroku. @Teshel touched on a couple of them:

- The `Procfile` changes the default behaviour of Heroku from `npm start` to `node dist/server/index.js` which doesn't exist when Heroku clones the repository. The way this works now will require you to run a build and deploy process outside of Heroku using a service like Travis.

To solve for this, simply remove the `Procfile` and trigger a build in Heroku. This will default to `npm start`, which by looking at the `prestart` task should trigger a webpack build before trying to start the server.

- If you're running builds on Heroku, the default behavior is to not install modules under `devDependencies`. So once Heroku runs `npm run build` it will fail immediately because the webpack module is unavailable.

The easiest way to override this is to set the `NPM_CONFIG_PRODUCTION` environment variable to `false`.

- The server is listening on the wrong port. Currently it is hardcoded to `3000` and Heroku expects the process to listen at the port the dyno instructs at runtime.

Swap this for `process.env.PORT || 3000` to keep it working on your local dev environment under port 3000 but substitute for the correct one on Heroku.

If it's helpful for anyone here, I've forked the repo and made the necessary modifications to allow a one click deployment on Heroku. You can find the repository here: https://github.com/Ignigena/universal-starter

Or:

[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/Ignigena/universal-starter)

**Comment by matiishyn** [comment]
Deploy still doesn't work, but it's an issue that we also have locally: https://github.com/angular/universal-starter/issues/176

Somehow it can be fixed locally (https://github.com/angular/angular-cli/issues/2234#issuecomment-248174857) but doesn't help for Heroku:

![image](https://cloud.githubusercontent.com/assets/3661065/18674262/e58b8350-7f4e-11e6-94c1-3ff9f2b8f755.png)

**Comment by jeffwhelpley** [comment]
This is similar to #128. @MarkPieszak we should have a guide for the most popular platforms and see what has to change in the lib to make it easier.

**Comment by jeffwhelpley** [comment]
I am consolidating this with #128. In short, we need to create some documentation and potentially config changes to make it easier to deploy to a number of target environments including Heroku.

**Comment by tabvn** [comment]
If you are using Universal CLI  i can recommend this video how to deploy Angular 2 Universal App to Heroku https://www.youtube.com/watch?v=GgWvuBdatAM
