### ISSUE TITLE
npm start should watch client and server

### ISSUE THREAD

**Issue by prabirshrestha** [angular/universal-starter#125]
Should npm start be this instead so we don't have to open two windows. One to watch server and another to watch client.

```
"start": "npm-run-all --parallel server watch"
```

I'm using `npm-run-all` npm package to run scripts parallel in cross platform way.

Unfortunately wepback is run twice - one in `prestart` and another in `watch` but this is already happening when opening two windows.

**Comment by MarkPieszak** [comment]
Hey we've updated this starter to include a `CLI` and a standalone webpack example using the latest `@angular/platform-server` that's been moved into Core. Closing this out since it's relating to the previous version, angular2-universal, but feel free to open a new issue if there's still an issue with the new version! Thanks.
