### ISSUE TITLE
Support for file loader (loading html through file loader)

### ISSUE THREAD

**Issue by LennardWesterveld** [angular/universal-starter#134]
Hello,

I was trying to get the webpack file loader work to get the templateUrl through the file loader.
So i changed this line of code in the commonConfig `{test: /\.html$/, loader: 'file?name=html/[name].[ext]?[hash]'},`.
Also i changed the line of codes where i use templateUrl to templateUrl: require('./app.component.html'), for example.

But i get the follow error when i try to startup the nodejs server:
Error: Cannot find module './app.component.html'

Is there any way to load the html by not chunk it to the js file with angular universal? because i used require nodejs tries to load it as a module. but its needs to resolve to a url for angular.

**Comment by jeffwhelpley** [comment]
@TheLarkInn @gdi2290 you guys have any ideas on this?

**Comment by gdi2290** [comment]
use `template: require('./app.component.html')`

**Comment by MarkPieszak** [comment]
Hey we've updated this starter to include a `CLI` and a standalone webpack example using the latest `@angular/platform-server` that's been moved into Core. Closing this out since it's relating to the previous version, angular2-universal, but feel free to open a new issue if there's still an issue with the new version! Thanks.
