### ISSUE TITLE
Hammerjs window undefined issue

### ISSUE THREAD

**Issue by flauc** [angular/universal-starter#189]
I've added hammerjs like this in my webpack: 

```ts
            new webpack.ProvidePlugin({
                Hammer: 'hammerjs',
            })
```
And everything works, however i get the window undefined error from the server. I know how to do DI Swapping and this is what i do when i need window usually but the problem here is that i think it's angular that is causing the error this time because this is the error i get: 

```ts
 ReferenceError: window is not defined
          at HammerGesturesPlugin.supports
```

Now as far as i can say it doesn't really break anything it just throws the error.

**Comment by MarkPieszak** [comment]
Thanks for reporting the issue! The problem is window is a Browser only object, at the moment you could do some conditional things such as isBrowser from Universal, to make sure it's not used on the server side pretender of your App.

You can follow the general issue here, where support for window and other globals will be attempted:
https://github.com/angular/universal/issues/534

**Comment by flauc** [comment]
Thank you for the quick response 👍

**Comment by gdi2290** [comment]
thanks, the current workaround was added to app.node.module

**Comment by ng-state** [comment]
Hi, having troubles to use Hammer with server side renderin. 
gdi2290 also cannot find app.node.module file to look for work around.
Is there any other possible solutions how to use it?

**Comment by Toxicable** [comment]
@ng-state if you have an issue it would be best to open an issue for it since this one is pretty outdated 

as for your second comment I have a proposal here: https://github.com/angular/universal/issues/828
Feel free to add any opinions on the matter there
