### ISSUE TITLE
Ignoring node_modules from webpack bundle

### ISSUE THREAD

**Issue by akshaybabajob** [angular/universal-starter#244]
Hi,

How can i prevent node_modules from getting bundled in the final bundle file? The file is getting huge.
I tried few plugins but they are not helpful and 'exclude' is also not working.

I also tried:
>externals: /^[^@.]/,
, but it is throwing error on browser console as angular2 is not defined.

Any help will be appreciated.

**Comment by Koslun** [comment]
`node_modules` contains all your dependencies, i.e. angular itself (so it won't be defined if you don't have any `node_modules`). So you can't really prevent that from being bundled in some way. Any plugins you use would only be able to tree-shake any of the parts that you're not using in your dependencies, discarding the parts of angular and other dependencies that you are not using.

You should however also be more specific about what bundle size you think is too big and what configurations or version of the starter you are using to get these results.

**Comment by akshaybabajob** [comment]
File size is going upto 9.5MBs and this are the dependencies:

>
"@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "2.0.0",
    "@angular/router": "3.0.0",
    "angular2-express-engine": "~2.1.0-rc.1",
    "angular2-google-map-auto-complete": "^2.0.1",
    "angular2-platform-node": "~2.1.0-rc.1",
    "angular2-universal": "~2.1.0-rc.1",
    "angular2-universal-polyfills": "~2.1.0-rc.1"
>

**Comment by Koslun** [comment]
@akshaybabajob Those are all necessary. The problem is that they are included over and over again. Which is ok when you're developing as it loads fast locally anyway. For production you will however want another webpack configuration that uses a lot more optimizations, which might take a little while to run, thus the reason why we normally don't run them all during development.

For production you probably want to look at the configurations of other starters such as https://github.com/AngularClass/angular2-webpack-starter & https://github.com/qdouble/angular-webpack2-starter. 

The most important optimization is using `UglifyJsPlugin`. Which you for instance can see done in the production config file of `angular2-webpack-starter` by AngularClass:  https://github.com/AngularClass/angular2-webpack-starter/blob/master/config/webpack.prod.js.

I.e. add this to your plugins array in your production config:
```javascript
new UglifyJsPlugin({
        // beautify: true, //debug
        // mangle: false, //debug
        // dead_code: false, //debug
        // unused: false, //debug
        // deadCode: false, //debug
        // compress: {
        //   screw_ie8: true,
        //   keep_fnames: true,
        //   drop_debugger: false,
        //   dead_code: false,
        //   unused: false
        // }, // debug
        // comments: true, //debug


        beautify: false, //prod
        mangle: {
          screw_ie8: true,
          keep_fnames: true
        }, //prod
        compress: {
          screw_ie8: true
        }, //prod
        comments: false //prod
      }),
```
Probably also want to include the LoaderOptionsPlugin, removing the tslint option inside it if you don't have tslint included in the project.

**Comment by akshaybabajob** [comment]
Okay but then can we keep node_modules in one bundle and the rest in another one?

**Comment by gdi2290** [comment]
for the server we need to include the universal/client packages until the resolution logic is better for angular. We can probably fix this by manually pointing to the correct "module" format for the server to avoid the umd bundle
