### ISSUE TITLE
Import css stylesheet

### ISSUE THREAD

**Issue by antiPoP** [angular/universal-starter#256]
I want to use bootstrap and right now I'm loading it from a CDN but seems the proper way is using npm and loading it through Webpack, but all my tries have been unsuccessful.

Using `import 'bootstrap/dist/css/bootstrap.min.css';` in client.ts seems to add bootstrap`as string, but the styles are not applied, so I would appreciate some help here.

**Comment by viktorstaikov** [comment]
Hi,

What was your solution?

**Comment by MuhammadZaidSE** [comment]
anybody resolved the issue?

**Comment by argirok** [comment]
On 16 Nov 2016 21:18, "antiPoP" <notifications@github.com> wrote:

I want to use bootstrap and right now I'm loading it from a CDN but seems
the proper way is using npm and loading it through Webpack, but all my
tries have been unsuccessful.

Using import 'bootstrap/dist/css/bootstrap.min.css'; in client.ts seems to
add bootstrap`as string, but the styles are not applied, so I would
appreciate some help here.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/angular/universal-starter/issues/256>, or mute the
thread
