### ISSUE TITLE
External stylesheets server-side rendering

### ISSUE THREAD

**Issue by antiPoP** [angular/universal-starter#257]
I'm trying to add bootstrap.css. In webpack.config.js I replaced
```javascript
{ test: /\.css$/, loader: 'raw-loader' },
```
with
```javascript
{ test: /\.css$/, loaders: ["style-loader", "css-loader"] },
```
then I installed the required dependencies:
```shell
npm i bootstrap --save
npm i css-loader url-loader file-loader style-loader --save-dev
```
and finally I added in client.ts and client.aot.ts:
```javascript
import 'bootstrap/dist/css/bootstrap.min.css';
```

That works for client side rendering, but server side does not include the bootstrap styles. How can these be included?

**Comment by Andrey-Pavlov** [comment]
@gdi2290 Hi, man. Can you help us how to use 'bootstrap-loader' and 'font-awesome-loader' on server side?

**Comment by Lukec1** [comment]
+1 for scss bootstrap

**Comment by MuhammadZaidSE** [comment]
Did anyone solved the problem?

**Comment by PTC-JoshuaMatthews** [comment]
So many suggestions here where to start...

**Comment by MarkPieszak** [comment]
Hey we've updated this starter to include a `CLI` and a standalone webpack example using the latest `@angular/platform-server` that's been moved into Core. Closing this out since it's relating to the previous version, angular2-universal, but feel free to open a new issue if there's still an issue with the new version! Thanks.
