### ISSUE TITLE
Long running "CanActivate"

### ISSUE THREAD

**Issue by dipunm** [angular/universal-starter#298]
Hey guys,

I hope this is the appropriate place to get a solution, but I have found that the preboot kicks in too early on the client side when there is a long running CanActivate.

User goes to `/dashboard`
Server cannot authenticate user (no session found) so it renders the /login page (btw, on a side note, can I make it do a redirect instead?)
1. App starts initialising.
2. AppComponent is initialised but contains a `<router-outlet>`
3. Router decides to render the `/dashboard` page, but realises there is a CanActivate guard.
4. Guard checks for a session by making an API call (sees that there is no session)
5. Guard tries to get an Auth0 token (uses an IFrame, may be a potential cause , returns an Observable) <-- this step is skipped on the server side.
6. Guard makes same decision to redirect to `/login`.

Unfortunately, somewhere before the Guard has finished making its decision, the pre-boot kicks in.
This leads to:
User sees login page.
User sees page with nothing in content area.
User sees login page.

I am going to look into a different user flow/solution, however, I thought it might be a good idea to post this problem here in the hope it may spark some ideas/discussions.

**Comment by afganhalbana** [comment]
@dipunm  Well as i try the authentication thing in angular 2 server side rendering, i faced the same issue which makes me do another approach like -> you call an API end point on the same server where your angular 2 application live, and save (in this case the token) in redis. This data that you've saved on redis will be the key to authenticating the user. So all you need to do now is to create the middleware on every routes that need to authenticate the user first. I don't know if this is a good approach or not, since i couldnt figured another solution in the mean time.  They said about the universal cookie which used DI but i havent found any propers documentation about that yet
