### ISSUE TITLE
Request: Enable HMR on Express Server

### ISSUE THREAD

**Issue by nicky-lenaers** [angular/universal-starter#314]
As I played around with this repo quite a bit, I'd like to see Hot Module Replacement (HMR) added by default. I am still experiencing issues enabling this on the existing ``express`` server using ``webpack-dev-middleware`` and ``webpack-hot-middleware`` combined with TypeScript.

I think it is good practice to have to enabled by default.

If not possible, any code example for the ``server.ts`` and ``webpack.config.ts`` to enable HMR would also be very much appreciated.

Thanks.

**Comment by flauc** [comment]
Did you maybe have some luck implementing it on your own?

**Comment by sangeet003** [comment]
Really need it anyone had success enabling hmr on this?

**Comment by nicky-lenaers** [comment]
Still haven't found a way to do this unfortunately. If anyone can be of help here, please suggest solutions!

**Comment by zmnv** [comment]
any solutions?

**Comment by mchambaud** [comment]
still nothing?

**Comment by MarkPieszak** [comment]
Hey we've updated this starter to include a `CLI` and a standalone webpack example using the latest `@angular/platform-server` that's been moved into Core. Closing this out since it's relating to the previous version, angular2-universal, but feel free to open a new issue if there's still an issue with the new version! Thanks.
