### ISSUE TITLE
ngfactory reloading page

### ISSUE THREAD

**Issue by sadeghipour** [angular/universal-starter#317]
Hi Guys,

I figure out that when page start loading somethings going wrong that cause reloading again!

In 767ms there is white rectangle that shows reloading the page again.
![ngfactory](https://cloud.githubusercontent.com/assets/7029205/21456089/f156e1d8-c92d-11e6-890a-e2ae2eefa7ea.JPG)

Any solution for this problem?

my router:
```javascript
export function getHomeModule() {
    return System.import('./home/home.module' + (process.env.AOT ? '.ngfactory' : ''))
        .then(mod => mod[(process.env.AOT ? 'HomeModuleNgFactory' : 'HomeModule')]);
}

@NgModule({
    imports: [
        RouterModule.forChild([
{path: 'home', loadChildren: getHomeModule}

        ])
    ],
})

export class AppRoutingModule {
}
```

**Comment by gdi2290** [comment]
This is how Angular's router handles lazy loading routes. When you prerender the app it has the whole app and when you send the app to the client it's going to remove the server view and request the async view from the server before rendering it

**Comment by paulogr** [comment]
Hey @gdi2290,

Is there any workaround for this?

Thank you.

**Comment by gdi2290** [comment]
preload the route before bootstrap

**Comment by paulogr** [comment]
I have to use some custom preload strategy? How to preload before boostraping angular?

**Comment by bmrinal** [comment]
The whole approach of replacing the client side app with server side pre rendered page looks flawed to me....there would always be a flicker and defeats the whole purpose. One way could be to patch the preboot to replay the routing on the existing server rendered page instead of replacing...Just a thought here. I am not OK with this kind of approach to replace with a flickr :(

**Comment by rquantz** [comment]
Why is this issue closed? It's nuts that this is considered acceptable.

**Comment by gdi2290** [comment]
@rquantz @bmrinal
Replacing the view rather than reusing it is by design of Angular's renderer which doesn't allow for hydration. The reason is that it's faster to render compared to reusing the view which has been true. The only reason to use hydration is for all of the edge cases that come with switching from SSR to CSR.

flickering was resolved (as from here: https://github.com/angular/angular/issues/15716)
with this extra option: 

`{initialNavigation: 'enabled'}` 

in 

`RouterModule.forRoot([], {initialNavigation: 'enabled'})`

Here https://angular.io/api/router/ExtraOptions#initialNavigation
Or here from the definition file:
``` javascript
/**
 * @whatItDoes Represents an option to configure when the initial navigation is performed.
 *
 * @description
 * * 'enabled' - the initial navigation starts before the root component is created.
 * The bootstrap is blocked until the initial navigation is complete.
 * * 'disabled' - the initial navigation is not performed. The location listener is set up before
 * the root component gets created.
 *
 * The 'enabled' option should be used for applications unless there is a reason to have
 * more control over when the router starts its initial navigation due to some complex
 * initialization logic. In this case, 'disabled' should be used.
 *
 *
 * @experimental
 */
export declare type InitialNavigation = 'enabled' | 'disabled';
```
