### ISSUE TITLE
How to rebuild on save ?

### ISSUE THREAD

**Issue by mostafamashayekhi** [angular/universal-starter#331]
I want when change some code in component and save auto build and browser auto refresh page , I found nodemon.json but it for html and css and scss but change not for .ts , 
i want increase speed coding ..
thanks for help me!

edit:
I think change `"start":"npm run server"` to `"start":"npm-run-all --parallel server watch"` fixed however is best solution ?

**Comment by MarkPieszak** [comment]
Hey we've updated this starter to include a `CLI` and a standalone webpack example using the latest `@angular/platform-server` that's been moved into Core. Closing this out since it's relating to the previous version, angular2-universal, but feel free to open a new issue if there's still an issue with the new version! Thanks.
