### ISSUE TITLE
How to set meta data in index.html

### ISSUE THREAD

**Issue by amitjain28** [angular/universal-starter#340]
Here i have seen angular2-meta.ts

but how can i set meta data for pages?
Also can it  update pages meta tags means can i see it when view the page source ? 

Thanks in advance

**Comment by matiishyn** [comment]
Hi
I had the same issue.
And I resolved it by adding few more methods to that Meta service:

```
import {DomAdapter, getDOM} from '@angular/platform-browser/src/dom/dom_adapter';
import {DOCUMENT} from '@angular/platform-browser';
...
export class Meta {
  private _dom: DomAdapter = getDOM();

  constructor( @Inject(DOCUMENT) private _document: any) { }
  /**
   * Sets the title of the page
   */
  setTitle(title: string) {
    this._document.title = title
  }

  /**
   * this.meta.updateMeta('description', 'test'); will  set <meta name="description" content="test">
   */
  updateMeta(name, content) {
    const head = this._document.head;
    let childNodesAsList = this._dom.childNodesAsList(head);
    let metaEl = childNodesAsList.find(el => el['attribs'] ? el['attribs'].name == name : false);
    if (metaEl) metaEl['attribs'].content = content;
  }
...
```

I hope it'll save you some time

**Comment by amitjain28** [comment]
After implementing the above code i got this error :

Can't resolve all parameters for Meta: (?).

How should i resolve it?

**Comment by matiishyn** [comment]
not sure what the error means, but this is my meta.ts: 
https://github.com/matiishyn/vs-seo/blob/master/src/angular2-meta.ts
you may try to copy it

**Comment by amitjain28** [comment]
After pasting this file there is no error.

But how will we change the meta dynamically for each page??

Do we need to call this "updateMeta()" in each component or we need to update anythng else?

**Comment by matiishyn** [comment]
it depends on your needs. You may call it on router events.

**Comment by MarkPieszak** [comment]
If it's crucial for all your components, I'd suggest subscribing to router NavigationEnd events, and pulling data from the event, updating the meta tags that way.

You can store data on a route by just adding an object:

    [ path : 'blah',  /* ... */  data : { title : 'page title', meta : { } } ]

That way you can just dynamically update all those things very easily, client and server side, right when Routes change.

**Comment by amitjain28** [comment]
@matiishyn Thanks
It works. Great. Once again thanks

**Comment by ScaryWolfMan** [comment]
@MarkPieszak 

Hi Mark.  Do you have an example?

So if I have some flow like going from`Browse Page` -> `Item Page`, then where should I put the logic to update tags?  For example, I have some description for the `Browse Page`, and then some item description for the `Item Page` for that particular item.

Thanks

**Comment by MarkPieszak** [comment]
You could either do it all yourself on a Page level, or through the routers events.

You could re-use the NavigationEnd event system I have here: https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Client/app/app.component.ts#L45-L71 just change it to use the `Title` class, and `Meta` class to set all your title/meta tags for you. (Basically change all the stuff in the .subscribe portion to Title/Meta setting code) That should do the trick!

**Comment by nicky-lenaers** [comment]
@amitjain28 Regarding your question 

> Also can it update pages meta tags means can i see it when view the page source ?

I assume you mean the updated meta-tags per route should be rendered server-side.
Did you pull this off? Because with the @matiishyn solution, it updates meta-tags, but not on the server-side.

If you guys know how to render the tags server-side, that'd be awesome!

**Comment by matiishyn** [comment]
@nicky-lenaers 
My solution should work on server-side,
at leats it works for me, otherwise it makes no sense for SEO :)
https://github.com/matiishyn/vs-seo/blob/master/src/angular2-meta.ts#L68 - this should work
but as you can see it's the 'update', so maybe you need those tags already present in index.html (may be empty), like I have here: https://github.com/matiishyn/vs-seo/blob/master/src/index.html#L9

If you need to create an element you may take a look how I do it for `canonical` - https://github.com/matiishyn/vs-seo/blob/master/src/angular2-meta.ts#L174

**Comment by Syldel** [comment]
Thank you @matiishyn ! Your solution works !

**Comment by StefanRein** [comment]
@matiishyn Thank you! Worked like a charm.

**Comment by djabif** [comment]
@matiishyn thanks for your solution, however it's not working for me. If I use `updateMeta("description", "my description")` it does put the meta when it runs the pre-render with Universal but then when I navigate through my web and click other routes, the `updateMeta("description", "my description") `doesn't update the existing meta because the  childNodesAsList elements don't have 'attribs' so 
` let metaEl = childNodesAsList.find(el => el['attribs'] ? el['attribs'].name == name : false);`  is always undefined.

I don't understand why when debugging it in the browser I see the "attribute" property in the meta elements but not the "attrib" property.
Why did you specify "attrib" instead of "attributes"?
Does this have anything to do with the angular-universal Parse5DomAdapter?

Maybe the representation of the DOM in universal differs from the representation of the DOM in the browser and your solution only works for the universal representation of the DOM (that's what my gut tells me, please correct me if I'm wrong).

Do you know what can be happening and how can I fix this? Thanks

**Comment by KSaiPrakash** [comment]
@matiishyn -- same issue as @djabif .. is there a fix to this ? getting a undefined to this -
let metaEl = childNodesAsList.find(el => el['attribs'] ? el['attribs'].name == name : false);
 

tried to iterate thru the ChildNodesList to find meta element ? is this the right approach ? is so how can we read HTMLObject as I am getting a TypeError: Converting circular structure to JSON

would appreciate if you had a similar experience.

Calling out to anyone who has faced a similar issue for their contributions.

**Comment by jrmcdona** [comment]
No reason we couldn't exted the meta service to add dynamic <script> or <link> tags from external service right?

**Comment by SumanSingh4** [comment]
Hii,

@matiishyn  I have tried your approach, but I didn't get el['attribs'] varible as explained by @djabif, I am facing same.
After using attribute in place of attribs, I have done somthing like this:-

childNodesAsList.forEach(el => {
            if(!!el.attributes){
                var varb = el.attributes.getNamedItem('name');
                var content = el.attributes.getNamedItem('content');
                if(!!varb){
                    if(varb.value == 'image'){
                        content.value = 'hello';
                        el.attributes.setNamedItem(content)
                    }
                }
            }
        });

Now, changes is reflecting in element in browser debugger, but not in view source page.
My main aim is to reflect in source page.
Any idea how I can do it??

Thanks

**Comment by MarkPieszak** [comment]
You can use the `Meta` service directly and update whatever you need @SumanSingh4

**Comment by furcino** [comment]
Hello, I was looking for the solution too. Just build an angular5 project and wanted seo to work with angular-universal. I didn't find it here so I am adding it:

```
import { Component } from '@angular/core';
import { Title, Meta, MetaDefinition } from '@angular/platform-browser';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  public constructor(public meta: Meta, public pageTitle: Title) {
    pageTitle.setTitle("MySite.COM");
    const keywords: MetaDefinition = {
      name: "keywords",
      content: "angular2, java, javaEE, angular-universal"
    }
    const description: MetaDefinition = {
      name: "description",
      content: "This is a description"
    }
    this.meta.addTags([keywords, description]);
  }

  title = 'app';
}

```

So people can find this: 

I wanted to **change meta tags and page title in angular5 during the prerender phase**. That led me to here. I finally just started searching the documentation and the solution was there clear as day. The solution lets you even **change meta tags and page title dinamically in angular5**. This is just for demonstration purposes. **The code for meta tag update and page title update needs to be probably moved** in the real application.

**Comment by herzinger** [comment]
Sorry if I'm asking a dumb question, but does this stuff from `@angular/platform-browser` work in the universal prerender phase? It just sounds a bit unintuitive, so I though of asking.

**Comment by meeraPurohit** [comment]
Hey, @matiishyn I using angular 5, I implemented DomAdapter, on run time, I got error 
**Module not found: Error: Can't resolve '@angular/platform-browser/src/dom/dom_adapter'** .
When I searched for this, I came to know that this is a private API.
Do you have any other alternatives for this?

**Comment by tskweres** [comment]
Has anyone discovered a way to set meta tags and title on the server side before render?

**Comment by stefanmorcodeanu** [comment]
Make sure to have imported these 2 files/modules
```
// These are important and needed before anything else 
import 'zone.js/dist/zone-node'; <br>
import 'reflect-metadata';
```
