### ISSUE TITLE
Make http request after preboot completes

### ISSUE THREAD

**Issue by prashant1587** [angular/universal-starter#374]
This question is not an issue rather than a question.

I want to call the http service after preboot completes  after Coordinate transfer of state from server to client view.

Could you help me how to i know the point when transfer of state from server to client is done.

thanks

**Comment by gdi2290** [comment]
when angular bootstraps that's when preboot is done

**Comment by imraqes** [comment]
Hi PatrickJS, 

So after application bootstrapped, I am calling a get API and showing the result on web page, now the page content has changed due to get request but when I go & check the page source this new data is not visible there.

Any thought on this would be very appreciable.

Thanks

**Comment by singhmohancs** [comment]
@imraqes do you see any warning or error in terminal when this request is made?

**Comment by imraqes** [comment]
@singhmohancs No I don't see any error but I don't see the dynamically generated content on view page source(CTRL + U).

**Comment by imraqes** [comment]
@gdi2290 sometimes when I scroll my application preboot doesn't complete, I can see 2 <app-root> in browser elements one as hidden, also I can't see all the things which are hidden on isBrowser, and events also doesn't work. This happens when I open too many tabs continuously on my browser, I realized this is because of preboot doesn't complete automatically, but I could not able to find how to manually complete preboot, I have done following code for manually preboot complete:

                  ```
if(window['prebootData'].apps.length){
				
				console.log('Dispatch new PrebootComplete main ts')
				setTimeout(()=>{
					const completeEvent = new Event('PrebootComplete');
            		window.document.dispatchEvent(completeEvent);
            	}, 3*1000);
			}

            window.document.addEventListener('PrebootComplete', () => {
                console.log('Preboot Complete main ts!!');

                console.log('main ts replay events');
				BrowserPrebootModule.replayEvents();
            });	
```
