### ISSUE TITLE
Upgrade to Angular version 4 timeline

### ISSUE THREAD

**Issue by hakonamatata** [angular/universal-starter#376]
Hi

First of, great work on server side rendering with Angular! It is crustal for my project to be able to change title and meta data for each page and that the google/facebook/twitter/pinrest web crawlers can pick this up, not just "loading".

Just wondering if there is a plan for upgrading to using version 4 of Angular any time soon?

**Comment by aitboudad** [comment]
https://github.com/angular/angular/issues/13822#issuecomment-282239301

**Comment by MarkPieszak** [comment]
Yes we should be upgrading the project once 4.0 comes out and is more stable, you can see a mini-demo of 4.x in action here if you'd like to see parts of it sooner (note the official expressEngine will come from Core as well soon). (https://github.com/FrozenPandaz/ng-universal-demo)

**Comment by MarkPieszak** [comment]
https://github.com/angular/universal-starter/pull/358 Should be merged in shortly

**Comment by MarkPieszak** [comment]
Hey we've updated this starter to include a `CLI` and a standalone webpack example using the latest `@angular/platform-server` that's been moved into Core. Closing this out since it's relating to the previous version, angular2-universal, but feel free to open a new issue if there's still an issue with the new version! Thanks.
