### ISSUE TITLE
Remove beta packages in package.json and workaround files

### ISSUE THREAD

**Issue by amitjain28** [angular/universal-starter#380]
Can we remove beta packages :
"rxjs": "5.0.0-beta.12",
 "webpack": "2.1.0-beta.27",
   "webpack-dev-server": "2.1.0-beta.11",

**Comment by amitjain28** [comment]
I have updated these packages:
"rxjs": "5.2.0",
"webpack": "2.2.0",
"webpack-dev-server": "2.2.0",

it works for JIT but not for AOT ?

**Comment by MarkPieszak** [comment]
The project should be updated to angular 4 and platform-server closer to when 4.0 gets released so those will all be fixed soon 🎈

**Comment by uharbachou** [comment]
Also will be good to describe how to transform from ng2 app to universal:) thank you

**Comment by anshulagarwal92** [comment]
I have created the project using this boiler plate and now it is about to complete, can anyone suggest me it's alternative to upgrade these packages to stable version

**Comment by amitjain28** [comment]
Yeah, i am facing the same issue. Just want to remove beta version packages. Can anyone let me know what stable version should i use to run project ?

**Comment by MarkPieszak** [comment]
Hey we've updated this starter to include a `CLI` and a standalone webpack example using the latest `@angular/platform-server` that's been moved into Core. Closing this out since it's relating to the previous version, angular2-universal, but feel free to open a new issue if there's still an issue with the new version! Thanks.
