### ISSUE TITLE
UNIVERSAL_CACHE is missing when component is included in the template

### ISSUE THREAD

**Issue by Liranius** [angular/universal-starter#388]
I have a page like this: 

```
import { Component, ChangeDetectionStrategy, ViewEncapsulation } from '@angular/core';

@Component({
    changeDetection: ChangeDetectionStrategy.Default,
    encapsulation: ViewEncapsulation.Emulated,
    selector: 'page-vision',
    template: `<vision-nav></vision-nav>`
})
export class PageVisionComponent { }
```

When page is refreshed, the console shows `Angular Universal: UNIVERSAL_CACHE is missing`. But when I removed the component tag of  `<vision-nav></vision-nav>`, the UNIVERSAL_CACHE will be as normal. Is there something wrong that I cannot import other components in the template?

**Comment by Liranius** [comment]
It turned out to be I forgotten wrapping DOM with { isBrowser }, never mind. Sorry for bothering.

**Comment by Skillnter** [comment]
@Liranius  Can you help me out? I still couldn't fix this issue.. Please describe me how you solved the issue.

**Comment by MarkPieszak** [comment]
Hey we've updated this starter to include a `CLI` and a standalone webpack example using the latest `@angular/platform-server` that's been moved into Core. Closing this out since it's relating to the previous version, angular2-universal, but feel free to open a new issue if there's still an issue with the new version! Thanks.
