### ISSUE TITLE
Directive not working in child components

### ISSUE THREAD

**Issue by Laurensvdmaas** [angular/universal-starter#390]
Directives are not working in child components, for example place the `xLarge` in the home template it will not work, anyone faced the same issue and knows a workaround?

**Comment by Laurensvdmaas** [comment]
You can close this, upon reading further i just had to import it in the shared.module..

**Comment by MarkPieszak** [comment]
Hey we've updated this starter to include a `CLI` and a standalone webpack example using the latest `@angular/platform-server` that's been moved into Core. Closing this out since it's relating to the previous version, angular2-universal, but feel free to open a new issue if there's still an issue with the new version! Thanks.
