### ISSUE TITLE
Why I must run ngc before build

### ISSUE THREAD

**Issue by viktorstaikov** [angular/universal-starter#394]
Hi
I noticed that I need to run ngc manually when changing files. Why is this necessary?
Otherwise "npm run build" produces errors about _browser.ngfactory_ and _node.ngfactory_.

**Comment by erginduran** [comment]
Both the JIT and AOT compilers generate an AppModuleNgFactory class from the same AppModule source code.

The JIT compiler creates that factory class on the fly, in memory, in the browser. The AOT compiler outputs the factory to a physical file that we're importing here in the static version of main.ts
[-more info-](http://stackoverflow.com/a/38933509/3287459) and [AoT](https://angular.io/docs/ts/latest/guide/universal.html)
<br />
Hope that it helps you

**Comment by MarkPieszak** [comment]
Hey we've updated this starter to include a `CLI` and a standalone webpack example using the latest `@angular/platform-server` that's been moved into Core. Closing this out since it's relating to the previous version, angular2-universal, but feel free to open a new issue if there's still an issue with the new version! Thanks.
