### ISSUE TITLE
Provide an alternative location for static files

### ISSUE THREAD

**Issue by bjwyse** [angular/universal-starter#40]
I don't think the project root should be used to serve static files as all files are then accessible (https://github.com/angular/universal-starter/blob/master/src/server.ts#L36).

I can see how some node_modules components need to be served but is there an alternative approach?

I also see some code in the universal project with these components hard coded (https://github.com/angular/universal/blob/master/modules/angular2-express-engine/src/engine.ts).

What is the future plan for these dependencies?

**Comment by gdi2290** [comment]
the hard coded logic in express engine will be removed and replaced (with NgScript) in the near future. We only needed it for e2e testing and shouldn't be used. The root is served because the repo had to be consistent with systemjs and the polyfills. For webpack because the files are bundled you only need to serve the dist folder so long as the index.html is also copy/moved to dist

**Comment by gdi2290** [comment]
I'm going to close this but feel free to open the issue in https://github.com/angular/universal and track https://github.com/angular/universal/issues/309
