### ISSUE TITLE
Reload on IIS not Working

### ISSUE THREAD

**Issue by waynecaruana** [angular/universal-starter#410]
Hi, 

When deploying the app to IIS is it normal that when assessing the URL directly the page is not found. 
This issue also happens when refreshing the web page. 

Is this an issue from your end or I'm doing something wrong? Please find a screenshot below.

![error404](https://user-images.githubusercontent.com/9405570/29071654-d2e04d32-7c44-11e7-822d-c01267601c14.PNG)

**Comment by MarkPieszak** [comment]
Hey we've updated this starter to include a `CLI` and a standalone webpack example using the latest `@angular/platform-server` that's been moved into Core. Closing this out since it's relating to the previous version, angular2-universal, but feel free to open a new issue if there's still an issue with the new version! Thanks.
