### ISSUE TITLE
CLI Version

### ISSUE THREAD

**Issue by flauc** [angular/universal-starter#450]
Thank you for the great starter 👍 

I must be missing something obvious, but I can't seem to figure out how to run both server and client in development mode?

**Comment by Toxicable** [comment]
Right now we only show using Universal in production mode since your a application should work example the same on server as browser, is there something you specifically want to develop focused at the server environment?
While you could do something like `ng build --watch` which will keep building to your dist folder, it's not the best experience.

**Comment by flauc** [comment]
Well, I don't necessarily need the server to refresh but I need a way to access my API on the client, and for that I need the server lifted, but I usually call the API with an url like this '/api/something', so the app assumes it should go to 'localhost:4200/api/something' and I can't figure out how to do that. Do I need a proxy pass setup?

**Comment by Toxicable** [comment]
Yeah it sounds like proxy is the method you want if in production your Angular app will sit on the same host as your backend.
See https://github.com/angular/angular-cli/wiki/stories-proxy
for info on how to do that

**Comment by flauc** [comment]
Thank you for pointing me in the right direction 👍

**Comment by MarkPieszak** [comment]
Just make sure in the end (when going to prod) you pass a full URL, as the proxy is mainly there for development. Without the full URL you will get errors during SSR since we need an absolute URL when making requests there.
