### ISSUE TITLE
how to make a query using firebase?

### ISSUE THREAD

**Issue by stewwan** [angular/universal-starter#457]
```ts
  ngOnInit() {
    firebase.database()
      .ref('...')
      .orderByChild('...')
      .equalTo('...')
      .on('value', (snapshot) => {
        console.log('ok')
      }, (e) => {
        console.log(e)
      })
  }
```
running this code the page take a while and respond with ERR_RESPONSE until I hit refresh then the page loads fine.

the server prints the `ok` from `console.log`, but not render the page on first request. 

I'm using the CLI starter

any thoughts?

**Comment by Toxicable** [comment]
Angular waits for all async operations to complete before it renders.
`firebase` opens and holds open a websocket connection and for Angular to be able to render your application on the server this websocket connection must close, otherwise it will never render.
AngualrFire2 is working to support universal but right now `firebase` by itself does not

**Comment by stewwan** [comment]
ok thanks for the fast reply.

any idea for a workaround? like a http request between app and firebase..  would that work?

**Comment by Toxicable** [comment]
An Http request would work fine yeah

**Comment by stewwan** [comment]
ok many Thanks I will try!
