### ISSUE TITLE
How to retain css during transition?

### ISSUE THREAD

**Issue by filoxo** [angular/universal-starter#484]
I've gotten a CLI project that uses the techniques described in this repo for SSR. Mine is only slightly modified in that it renders an app shell that is delivered with the first request. I've found that the prerender script creates the following style tag:

```
<style ng-transition="my-app">.body{...}</style>
```
The above is bothersome to me for two reasons: I'd consider this "critical css" which should stay on the page and not be blown away by the app after transition, and this shouldn't be included in the browser bundle (why deliver the same CSS again). I've partially solved this by only including global styles (eg. `styles.scss`, in practice I'm using `critical.css`) in the server module and not in the browser module; this way the styles are not loaded again.

I still have to solve the first problem: how can I mark some CSS as not needing to be replaced on server transition? I found that the ng-transition directive is responsible for deleting the server-rendered styles. Removing it accomplishes what I need, but it'd be better to be able to mark some styles as not-ng-transition-removable.

**Comment by CaerusKaru** [comment]
Duplicate of https://github.com/angular/angular/issues/15716#issuecomment-298980082

**Comment by filoxo** [comment]
@CaerusKaru Thanks for the info, but I don't think this is a duplicate. My server module doesn't use routing and isn't lazily loaded at all. Additionally, I think this goes a little beyond that issue because I'm asking for the universal renderer to inline critical styles for _reuse_ in my app after its loaded as well for better performance.

**Comment by CaerusKaru** [comment]
To clarify: unless your server module completely ignores your browser module, i.e. does not import it, it necessarily uses routing in order to generate your components and render the HTML string. If your server module does ignore your browser module, then this issue is out of scope for the universal-starter because the starter was not designed with this functionality in mind, and your issue is better suited for StackOverflow.

If the first case is what's really happening, and you are importing your browser module and using routing, then adding the `initialNavigation` option does exactly what you want. When the module is rendered on the server, CSS is inlined into the rendered HTML and given universal-specific tags, which the browser looks for when `initialNavigation` is enabled, and reused when the browser module is bootstrapped. This happens both for regular rendering and lazy loading.

**Comment by filoxo** [comment]
Indeed my server module doesn't use the browser module at all; instead it renders the same components filled with placeholder components (like Facebook's feed does) which is what I consider the shell. Closing since this is "out of scope".
