### ISSUE TITLE
How to deploy Angular Universal to production (port 80)

### ISSUE THREAD

**Issue by calebeaires** [angular/universal-starter#514]
After make the app, how to deploy it? I see that on package.json there is many commands to build, but how to make it right to put on production in port 80?

```javascript
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build:client-and-server-bundles": "ng build --prod && ng build --prod --app 1 --output-hashing=false",
    "build:prerender": "npm run build:client-and-server-bundles && npm run webpack:server && npm run generate:prerender",
    "build:ssr": "npm run build:client-and-server-bundles && npm run webpack:server",
    "generate:prerender": "cd dist && node prerender",
    "webpack:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:prerender": "cd dist/browser && http-server",
    "serve:ssr": "node dist/server"
  }

```

**Comment by kalyan1102** [comment]
if you run "npm run build:ssr" it will create a dist folder which you will need to place on server. Additionally for some of the module dependencies, you also need to place package.json and run npm install to install node modules.

Once you are done with all these you can then run "npm run serve:ssr" ( better to use pm2 which will take this process and don't exit ) but it will start pointing to your server's 4000 port. You can install nginx which is better to give a proxy to port 4000 of your application. so Nginx port 80 but it will proxy to port 4000 in background. It always better to use a proxy for node app rather than directly exposing the app. You can also load balance between multiple app in this way.

**Comment by m98** [comment]
The @kalyan1102 answer is correct.

But here is the summery if you're confused:

1. `npm run build:ssr`
2. Move the `dist` over to your server
3. install [PM2](http://pm2.keymetrics.io/)
`      npm install pm2 -g |`
4. On your server, use PM2 to run the server bundled app
`      pm2 start dist/server.js`
5. If you're using Nginx, or other web servers, make sure to redirect requests to the port that the app started with PM2 is listening on.

**Comment by calebeaires** [comment]
Thanks @kalyan1102, @m98

**Comment by chozharajan** [comment]
@kalyan1102, @m98  i don't have knowledge in _nginx_ . we are hosting our project  in IIS web server. any one tell me how to host universal project in IIS server. for normal angular project i move all bundles in `dist` to `mywebsite/Allfiles` folder. but in universal i have two folder `server and browser`. i moved all files from server and browser. site works but universal not working(view source)....... **how to host universal project in IIS server**

**Comment by chazguerrero** [comment]
@chozharajan we host a universal app on iis in aure you need to add the below to your webconfig.
if you are hosting the iis server on your own hardware make sure you have the iisnode module installed
[iis-node github](https://github.com/tjanczuk/iisnode)

``` xml
 <system.webServer>
    <handlers>
      <add name="iisnode" path="server.js" verb="*" modules="iisnode" />
    </handlers>
    <iisnode watchedFiles="web.config" nodeProcessCountPerApplication="0" />
</system.webServer>
```

hope this helps!

**Comment by kamalakkanni** [comment]
@chazguerrero Thanks.I have installed iisnode and nodejs  in my production server.Tehn I put above lines in web.config.I got error as

403 - Forbidden: Access is denied.

I tried to fix this by changing my config as below

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
 
   <system.webServer>
    <handlers>
           <add name="iisnode" path="/server.js" verb="*" modules="iisnode"/>
     </handlers>
      <rewrite>
           <rules>
                <rule name="LogFile" patternSyntax="ECMAScript" stopProcessing="true">
                     <match url="iisnode"/>
                </rule>
                <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">
                    <match url="^/server.js\/debug[\/]?" />
                </rule>
                <rule name="StaticContent">
                     <action type="Rewrite" url="public{{REQUEST_URI}}"/>
                </rule>
                <rule name="DynamicContent">
                     <conditions>
                          <add input="{{REQUEST_FILENAME}}" matchType="IsFile" negate="True"/>
                     </conditions>
                     <action type="Rewrite" url="/server.js"/>
                </rule>
           </rules>
      </rewrite>
<iisnode        
      loggingEnabled="true"
        logDirectory="iisnode"
     />  
	  
  </system.webServer>
</configuration>


But I got error 

iisnode encountered an error when processing the request.

HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1002
HTTP reason: Internal Server Error
You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.

In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.

The node.exe process has not written any information to stderr or iisnode was unable to capture this information. Frequent reason is that the iisnode module is unable to create a log file to capture stdout and stderr output from node.exe. Please check that the identity of the IIS application pool running the node.js application has read and write access permissions to the directory on the server where the node.js application is located. Alternatively you can disable logging by setting system.webServer/iisnode/@loggingEnabled element of web.config to 'false'.




Pls help me

**Comment by kamalakkanni** [comment]
@chazguerrero  pls help us

**Comment by kamalakkanni** [comment]
whether I need to move all the files of dist?

**Comment by m98** [comment]
@mikkeldamm You need to move the `dist` directory to your server. If you're using an Express engine, you just need to start the `server.js` which exists on `dist` directory: `node dist/server.js`, it will run on a special port as you defined in your configuration (it should be 4000 if you use this repository)

On IIS, you need  to serve that IP and port, and also on all "not found" (`404`) pass it to that IP

**Comment by martinabrahams** [comment]
I found something odd when running on IIS with iisnode, which may help some people.

Normally when you perform a build everything goes into ./dist including server.js. When you run the application via npm this is where the server.js needs to live. 

However on IIS when wrapping via web.config it needs to have server.js moved to the root of the application (referencing ./dist/server.js as your entry point doesn't work, it results in all references becoming ./dist/dist/). This is using the out-of-the-box universal starter.  

IIS folder structure.
-
|- node_modules/
|- dist/
|- package.json 
|- server.js
|- web.config (as per @kamalakkanni 's provided example)

So when I package for our IIS environment I have an extra step to move the server.js out of dist and to the root. When I package for production (AWS EBS, I leave the file in dist).

PS: if there's a way to avoid this with additional configuration, I'd love to hear it.

**Comment by vijaycreatise** [comment]
the same issue with Apache server, can anyone please help. what configuration do we need to change in apache to work.

**Comment by kudikalasrikanth** [comment]
global.localStorage = new Proxy(instance, {
                          ^

ReferenceError: Proxy is not defined
    at Object.<anonymous> (/var/angular/dist/server.js:131240:27)
    at __webpack_require__ (/var/angular/dist/server.js:20:30)
    at Object.<anonymous> (/var/angular/dist/server.js:102:79)
    at __webpack_require__ (/var/angular/dist/server.js:20:30)
    at /var/angular/dist/server.js:84:18
    at Object.<anonymous> (/var/angular/dist/server.js:87:10)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

**Comment by fabrizziocht** [comment]
Using pm2, how can I change de port before running, I'm trying pm2 start dist/server.js -- --port 4001 but not works

**Comment by abrahamortiz** [comment]
Change the port in your server.js

**Comment by vbkmr09** [comment]
Change Port in server.ts
`PORT = process.env.PORT || 4000;
`TO
`const PORT = process.env.PORT || 8080;
`

**Comment by oantonov** [comment]
Well, the port number does not matter, what it does is that in the docroot you no longer have index.html, so I tried to make docroot  = docroot/dist/browser but then I get error 500 because server folder is outside docroot. I could not find any solution to that
FYI, make sure no matter port is your express server to make apache/nginx/whatever listen to that port, simply said make that server listen 4000/8080/whatever
