### ISSUE TITLE
WARNING in ./node_modules/@angular/core/fesm5/core.js

### ISSUE THREAD

**Issue by a13972848** [angular/universal-starter#579]
![555](https://user-images.githubusercontent.com/34478822/39660426-510a521a-5071-11e8-9663-2841b667e071.png)

In Angular 6; 
and 
npm run build:ssr && npm run serve:ssr

**Comment by Toxicable** [comment]
@a13972848 You can ignore that warning. It's nothing broken, it's simply @angular/router 's use of `System.import()`
You can track this more here: https://github.com/angular/angular/issues/21560

@linusbrolin Your issue is this open here: https://github.com/angular/universal/issues/982
It appears to be related to using `innerHTML`

**Comment by Toxicable** [comment]
I just put in a fix for this here
https://github.com/angular/universal-starter/pull/593
feel free to update your webpack config to have this extra line
