### ISSUE TITLE
Prerender build with 4 level nesting parameters 

### ISSUE THREAD

**Issue by PuriaRad** [angular/universal-starter#582]
For some reasons I want to create prerender build of my angular 5 project instead of server-side rendering.

There are 4 levels in my routes like this:

`example.com/category/:id/subcategory/:id/event/:id/ticket/:id`

Also, There is a rest api backend which I'm using for fetching data for each section. For example, /category/1 is sport, /category/1/subcategory/1 is football and so on.

**First question:** How can I create a html file for each of these levels by using `prerender.js` and How should my `static.paths.ts` look like?

**Second question:** How can I set meta tags for each of these pages?

**Third question:** How should my `app-routing.module` look like? Should I use children approach?

I'm using Angular 5.0.0 and ngx-restangular 2.0.2

Thank you.

**Comment by Toxicable** [comment]
This is not something Universal can solve for you.
You must know the exact path before you render your app when doing so, Universal cant do a lookup to see if a certain product exists or not.
I think SSR is a better case for you, since that's dynamic and as requests come in for certain products.

However if you did still want prerendering then you could possibly do a API query to find all products then loop over this list and render a page for each item.

(replace products with the name of your entity, it's just good for examples)
