### ISSUE TITLE
The client bundle code size is huge after optimizing

### ISSUE THREAD

**Issue by prayagmk** [angular/universal-starter#70]
The client bundle code is huge after optimization.
 new webpack.optimize.UglifyJsPlugin({
       mangle: false
    })

Its coming around 1.37 MB. 
Is there a way I can specify the angular common modules to be imported rather than importing everything?

**Comment by gdi2290** [comment]
you need to also include the source-map-loader for preLoaders (which I should add)and don't include all of rxjs

**Comment by mostlyjason** [comment]
It's 2.6 MB unoptimized. This is kind of crazy to me because one of the main attractions for universal code is the performance improvement, and yet we have this huge download and almost a third of a second parsing scripts, without even adding any business logic. Is there any way we can remove unneeded modules from the web pack config on the client side?

**Comment by gdi2290** [comment]
less code size is done with ngc by pre-compiling the app. This feature will be available in the near future.

**Comment by jeffwhelpley** [comment]
With AoT this issue is resolved
