### ISSUE TITLE
HTTP not working with latest version

### ISSUE THREAD

**Issue by joaogarin** [angular/universal-starter#89]
Hello,

I just pulled a fresh copy of the repo and the HTTP is not being rendered server side. I noticed because update my own project to @angular rc and latest universal. and then pulled a copy of the starter and same thing happened, the HTTP request is not being loaded in the server only when the client kicks in.

![screen shot 2016-05-21 at 10 56 11](https://cloud.githubusercontent.com/assets/2866604/15447441/bd4891e2-1f42-11e6-98f2-3f64768ecd58.png)

Best regard
Joao Garin

**Comment by joaogarin** [comment]
Might be related with latest comment here https://github.com/angular/universal-starter/issues/79

**Comment by felipedrumond** [comment]
I'm not sure which software platform you are interested in, but I'd suggest you looking at [https://github.com/aspnet/JavaScriptServices/tree/master/samples/angular/MusicStore](url)

I was trying to develop a website using universal and node.js, but definitely those guys on Microsoft are doing a great job to integrate angular 2 running at server.

**Comment by joaogarin** [comment]
I am using express like the starter repo.

**Comment by davidkaminsky** [comment]
I am seeing this as well.

**Comment by kylebuch8** [comment]
@joaogarin I'd try again now. @gdi2290 just pushed a release that addressed an http issue. Try updating to version 0.101.4 and run npm prune and npm install.

**Comment by davidkaminsky** [comment]
This still works pretty funky even after upgrading to 0.101.4. The problem is less evident now but still exists to some degree. Let me explain.

1) Start the server. Hit the "About" page. You see the about page immediately - looking at the source it's clearly server rendering the text 'This is the "About" page'.
2) Hit the "Home" page in a new tab. It renders the about page and switches to the home page. Looking at it's source you still see 'This is the "About" page' was rendered by the server.
3) Kill the server and start it again. Now hit the "Home" page first. It's correctly server rendered.
4) Now hit the "About" page, it's still server rendering the Home page and switching to the About page.

This isn't how it should be working is it? I'd assume if I directly hit the "Home" page it'll always server render the home page and if I directly hit the "About" page it'll always server render the home page. Right now it seems to depend on the state of the server in some way.

**Comment by gdi2290** [comment]
@davidkaminsky please track https://github.com/angular/universal/issues/421 which is the correct problem

**Comment by joaogarin** [comment]
sorry was out the last few days. I will track the progress there and try out the newer versions on my app to see how its doing;) tks
